stages:
  - cleanup
  - build
  - test

variables:
  GIT_REPO_URL: "https://$GITHUB_TOKEN@github.com/KevinBenoitt/cicd-sample-app.git"
  CLONE_DIR: "sample-app"



build_sample_app:
  stage: build
  script:
    - git clone $GIT_REPO_URL $CLONE_DIR
    - cd $CLONE_DIR
    - bash ./sample-app.sh
  tags:
    - docker

test_sample_app:
  stage: test
  script:
    - cd $CLONE_DIR
    - curl http://172.17.0.3:5050/ | grep "You are calling me from 172.17.0.2"
  tags:
    - docker
