stages:
  - 
  - cleanup
  - build
  - test

cleanup:
  stage: cleanup
  script:
    - docker stop samplerunning || true
    - docker rm samplerunning || true
  tags:
    - shared

build_sample_app:
  stage: build
  script:
    - mkdir -p $CLONE_DIR
    - cd $CLONE_DIR
    - curl -O $GITHUB_REPO_URL/sample-app.sh
    - bash ./sample-app.sh
  tags:
    - shared

test_sample_app:
  stage: test
  script:
    - cd $CLONE_DIR
    - curl http://172.17.0.3:5050/ | grep "You are calling me from 172.17.0.2"
  tags:
    - shared
