stages:
  - mirror
  - cleanup
  - build
  - test

variables:
  GITHUB_REPO_URL: "https://raw.githubusercontent.com/KevinBenoitt/cicd-sample-app/main"
  CLONE_DIR: "sample-app"
  
mirror_from_github:
  stage: mirror
  script:
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git clone https://your-github-username:your-pat@github.com/KevinBenoitt/cicd-sample-app.git
    - cd cicd-sample-app
    - git remote add gitlab https://gitlab.example.com/your-group/your-project.git
    - git push gitlab master
  only:
    - schedules
cleanup:
  stage: cleanup
  script:
    - docker stop samplerunning || true
    - docker rm samplerunning || true
  tags:
    - shared

build_sample_app:
  stage: build
  script:
    - mkdir -p $CLONE_DIR
    - cd $CLONE_DIR
    - curl -O $GITHUB_REPO_URL/sample-app.sh
    - bash ./sample-app.sh
  tags:
    - shared

test_sample_app:
  stage: test
  script:
    - cd $CLONE_DIR
    - curl http://172.17.0.3:5050/ | grep "You are calling me from 172.17.0.2"
  tags:
    - shared
